# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-04 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191203_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bdate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='my_site',
        ),
        migrations.RemoveField(
            model_name='account',
            name='odnoklassniki',
        ),
        migrations.RemoveField(
            model_name='account',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vkontakte',
        ),
    ]
