version: '2'

services:
  secretsanta-app:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    # ports:
    #   - "8000:8000"

  nginx-front:
    image: nginx
    volumes:
      - ./nginx-front.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    volumes_from:
      - "secretsanta-app"
