# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Presentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecretSanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='presentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Presentee'),
        ),
    ]
