# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='presentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_presentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gift',
            name='santa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_santa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Presentee',
        ),
    ]
