# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161222_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecretSanta',
            new_name='SecretSantaEvent',
        ),
    ]
